### ISSUE TITLE
Extra property on output after pipeing .csv 

### ISSUE THREAD

**Issue by r-powar** [julien-f/csv2json#6]
We are getting the following output 

``` javascript
{
Primary Key: "Parental Control",
LaunchToolKitLabel: "Article: Comcast Parental Controls Policy",
LaunchToolURI: "http://einstein.cable.comcast.com/Einstein/ViewDocument/POL1075",
LaunchItgLabel: "",
timeline consumer ID: "",
: "" //this is the extra property 
}
```

Is it more likely that this library has a problem or are our csv file has a phantom column?

**Comment by julien-f** [comment]
I believe that there is indeed a phantom column in the CSV.

But what's really problematic is the fact that this JSON is invalid because the key of the last item should be quoted…

_Edit: Unless this is not the raw output because all keys should be quoted in JSON and non of them are in you example._

**Comment by r-powar** [comment]
Thanks julien-f, that was not a raw output. But as far the extra key, i believe that issue shows up when the file is initially converted to the .csv, thats what it looks like.

Thanks again
